import './globals.css';
import { primary } from '@/app/ui/fonts/fonts';

import { AppWrapper } from '@/app/providers/AppWrapper';
import { Header } from '@/app/ui/ui';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr" className={` ${primary.variable} text-primary-dark`}>
      <body suppressHydrationWarning={true}>
        <AppWrapper>
          {' '}
          <Header />
          <main>
            <div className="main-wrapper main-container">{children}</div>
          </main>
        </AppWrapper>
      </body>
    </html>
  );
}
